# Websocket Local: ws://localhost:8000/ws/agent
# local : uvicorn app.api.websocket_server:app --host 0.0.0.0 --port 8000
# Guardrail:
guardrails:
  sql_injection:
    enable: true
    patterns: 
      - "(?i)\\b(drop|delete|truncate|alter)\\s+(table|database)\\b"
      - "(?i);\\s*(drop|delete|update|insert)\\b"

# research agent
research:
  google_api_key: "${GOOGLE_API_KEY}"
  google_cse_id: "${GOOGLE_CSE_ID}"
  num_results: 5
  max_urls_to_read: 3
  fetch_timeout_seconds: 10
  max_chars_per_pages: 5000
  Google_API_Point : "${GOOGLE_API_POINT}"
  serper_key: "${SERPER_KEY}"

# pii masking
pii_masking :
  enabled: True
  rules: 
    - name: "Email"
      pattern: "[a-zA-Z0-9.%+-]+@[a-zA-Z0-9.-]+\\[a-zA-Z]{2,}"
      mask: "[Email]"
    - name: "Phone"
      pattern: "(?:\\+91[\\-\\s]?)?[6-9]\\d{9}"
      mask: "[Mobile Number]"

# Evaluation
evaluation:
  enabled: true
  store: "postgres"
  table_name: "${POSTGRES_AGENT_DB}"
  cloudwatch_log: true

# postgre
postgre:
  host: "${POSTGRES_HOST}"
  port: "${POSTGRES_PORT}"
  database: "${POSTGRES_DB}"
  user: "${POSTGRES_USER}"
  password: "${POSTGRES_PASSWORD}"
  allowed_tables:
    - "orders"
    - "products"
    - "customers"
    - "order_items"

# opensearch
opensearch:
  host: "${OPENSEARCH_HOST}"
  index_name: "${OPENSEARCH_INDEX}"
  use_aws_auth: "${USE_AWS_OPENSEARCH}"
  embedding_model:  "${BEDROCK_EMBEDDING_MODEL_ID}"
  embedding_dimensions: 1024
  top_k : 5
  region: "${AWS_REGION}"
  openai_api_key : "${OPENAI_API_KEY}"

# bedrock
bedrock:
  service : "bedrock-runtime"
  region : "${AWS_REGION}"
  model_id: "${BEDROCK_LLM_MODEL_ID}"
  temperature: 0.0 
  max_tokens: 2048

# routing keywords:
routing:
  sql :
    - "how many"
    - "orders"
    - "order status"
    - "products"
